In [2]:
# 1. Import the numpy package under the name np

import numpy as np


# 2. Print the numpy version and the configuration 

np.__version__

'1.24.3'

In [5]:
# Create a null vector of size 10

zero_vector = np.zeros(10)

print(zero_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [6]:
# 4. How to find the memory size of any array

print(f'the size of the zero vector array its {zero_vector.size}')
print(f'the Memory size of one element of the array in bytes its {zero_vector.itemsize}')
print(f'Memory size of the numpy array in bytes its {zero_vector.size * zero_vector.itemsize}')

the size of the zero vector array its 10
the Memory size of one element of the array in bytes its 8
Memory size of the numpy array in bytes its 80


In [9]:
# 5. How to get the documentation of the numpy add function from the command line?

# print((help(np.add)))
# print('\n')
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [11]:
# Create a null vector of size 10 but the fifth value which is 1

vector_1 = np.zeros(10)
vector_1[4] = 1

print(vector_1)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [12]:
# 7. Create a vector with values ranging from 10 to 49 

vector_2 = np.arange(10,50)
print(vector_2)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [16]:
# Reverse a vector (first element becomes last)

print((vector_2[::-1]))


[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [17]:

# 9. Create a 3x3 matrix with values ranging from 0 to 8 

M = np.arange(9).reshape(3,3)
print(M)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [21]:
# 10. Find indices of non-zero elements from [1,2,0,0,4,0]

v = np.array([1,2,0,0,4,0])
mask = v != 0 # mascara booleana 
print(v[mask])

[1 2 4]


In [23]:
#  11. Create a 3x3 identity matrix

I = np.identity(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [33]:
# 12. Create a 3x3x3 array with random values 

print(np.random.randint(100,120, size= (3,3,3)))


[[[101 116 101]
  [117 103 116]
  [106 109 118]]

 [[101 100 105]
  [105 106 106]
  [118 114 117]]

 [[118 104 105]
  [107 100 114]
  [106 113 106]]]


In [39]:
# 13. Create a 10x10 array with random values and find the minimum and maximum values 

rand_M = np.random.random(size=(10,10))
print(rand_M)
print('\n')
print(f'the minimun its {rand_M.min()}')
print(f'the maximum its {rand_M.max()}')

[[0.8162536  0.14268305 0.94878318 0.27559915 0.48125109 0.27435672
  0.44371829 0.61983585 0.88344728 0.85077123]
 [0.6692388  0.01167111 0.04789929 0.88272903 0.17747811 0.45307792
  0.43497803 0.31324801 0.4613273  0.781937  ]
 [0.79678886 0.12409671 0.65040957 0.40241599 0.11975035 0.17198289
  0.15562137 0.52240041 0.75570701 0.56564907]
 [0.91476136 0.36766371 0.3352931  0.84570703 0.09343202 0.42530819
  0.90393173 0.79953212 0.58580668 0.84810165]
 [0.63895239 0.71724098 0.39620579 0.92225294 0.52490045 0.95329069
  0.18746674 0.19745274 0.72913961 0.77304188]
 [0.44527443 0.36183122 0.04425869 0.68137373 0.46120965 0.58800827
  0.55048144 0.10579654 0.91457628 0.84803759]
 [0.25478507 0.49207669 0.55893248 0.5646067  0.53236463 0.93630668
  0.8951932  0.83757439 0.35404977 0.37459453]
 [0.51939888 0.32946413 0.56579681 0.82375485 0.86979009 0.15394213
  0.07740228 0.39839897 0.51076193 0.6450594 ]
 [0.00997364 0.9534953  0.71258916 0.57396473 0.19432046 0.70428246
  0.51336412

In [40]:
# 14. Create a random vector of size 30 and find the mean value

print(np.random.random(size= 30).mean())

0.46475445402549936


In [44]:
# 15. Create a 2d array with 1 on the border and 0 inside

arr_2d = np.zeros(25).reshape(5,5)
arr_2d[0,:] = 1
arr_2d[-1,:] = 1
arr_2d[:,0] = 1
arr_2d[:,-1] = 1
print(arr_2d)



[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [50]:
# 16. How to add a border (filled with 0's) around an existing array? 

v1 = np.ones((3,3))
print(v1)
print('\n')

v1 = np.pad(v1, pad_width=1, mode= 'constant', constant_values=0)
print(v1)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [53]:
# 17. What is the result of the following expression?

print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


In [5]:

# 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
d = np.diag(np.arange(1,5), k=-1) 
# k : int, optional
# Diagonal in question. The default is 0. Use k>0 for diagonals above the main diagonal, and k<0 for diagonals below the main diagonal.
print(d)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [73]:
# Create a 8x8 matrix and fill it with a checkerboard pattern 
check = np.zeros((8,8))
check[1::2,::2] = 1 # desde la fila 1 hasta el final de una si una no, y desde la columna 0 hasta la utlima de una si otra no
                    # el problema es que son pares y por eso hay que hacer el siguiente paso

check[::2,1::2] = 1 # desde la fila 0 hasta la ultima haciendo una si otra, y la columna 1 hasta la ultima una si, una no
print(check)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [80]:
# 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 

arr = np.arange(6*8*7).reshape(6,7,8)

print(arr)
print('\n')

print(np.unravel_index(100, (6,7,8))) # dado unas un array de dimensiones x, y, z me devuelve las coordenadas del enesimo elemento del array
print('\n')
print(arr[1,5,3])

[[[  0   1   2   3   4   5   6   7]
  [  8   9  10  11  12  13  14  15]
  [ 16  17  18  19  20  21  22  23]
  [ 24  25  26  27  28  29  30  31]
  [ 32  33  34  35  36  37  38  39]
  [ 40  41  42  43  44  45  46  47]
  [ 48  49  50  51  52  53  54  55]]

 [[ 56  57  58  59  60  61  62  63]
  [ 64  65  66  67  68  69  70  71]
  [ 72  73  74  75  76  77  78  79]
  [ 80  81  82  83  84  85  86  87]
  [ 88  89  90  91  92  93  94  95]
  [ 96  97  98  99 100 101 102 103]
  [104 105 106 107 108 109 110 111]]

 [[112 113 114 115 116 117 118 119]
  [120 121 122 123 124 125 126 127]
  [128 129 130 131 132 133 134 135]
  [136 137 138 139 140 141 142 143]
  [144 145 146 147 148 149 150 151]
  [152 153 154 155 156 157 158 159]
  [160 161 162 163 164 165 166 167]]

 [[168 169 170 171 172 173 174 175]
  [176 177 178 179 180 181 182 183]
  [184 185 186 187 188 189 190 191]
  [192 193 194 195 196 197 198 199]
  [200 201 202 203 204 205 206 207]
  [208 209 210 211 212 213 214 215]
  [216 217 218 219 220

In [12]:
# 21. Create a checkerboard 8x8 matrix using the tile function

arr = np.tile([[0,1],[1,0]],(4,4))
arr

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [18]:
# 22. Normalize a 5x5 random matrix (★☆☆)
a = np.random.random((5,5))
a_norm = (a - a.mean())/a.std()
a_norm

array([[-1.2629887 , -1.14087094, -0.48977558, -0.62675197,  0.70910209],
       [-0.77830112, -0.76624223, -1.04795635,  0.20364287,  0.21733286],
       [-0.61607686,  1.8646537 , -0.04532168,  0.17789807, -1.13848649],
       [ 0.59137233,  0.15655424, -0.76885404, -0.91391248,  1.98339146],
       [ 1.93966376,  1.89616152, -0.34293639,  0.39269392, -0.19399198]])

In [19]:
a = np.dtype([('r', np.ubyte),
              ('g', np.ubyte),
              ('b', np.ubyte),
              ('a', np.ubyte)])
a

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [24]:
# 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) 

np.random.seed(42)
M1 = np.random.randint(low= -10, high= 10, size= (5,3))
M2 = np.random.randint(low= -10, high= 10, size= (3,2))
print(M1)
print('\n')
print(M2)
print('\n')
M1 @ M2

[[-4  9  4]
 [ 0 -3 -4]
 [ 8  0  0]
 [-7 -3 -8]
 [-9  1 -5]]


[[ -9 -10]
 [  1   1]
 [  6  -1]]




array([[ 69,  45],
       [-27,   1],
       [-72, -80],
       [ 12,  75],
       [ 52,  96]])

In [28]:
# 25. Given a 1D array, negate all elements which are between 3 and 8, in place
arr = np.random.randint(low= 0 , high= 10, size= (1,10))
print(arr)
condition = (3 < arr) & (arr < 8)

np.where(condition,-arr, arr)

[[5 5 9 3 5 1 9 1 9 3]]


array([[-5, -5,  9,  3, -5,  1,  9,  1,  9,  3]])

In [32]:
#26. What is the output of the following script?
print(sum(range(5),-1))
from numpy import *
print(sum(range(5), -1))

10
10


In [42]:
# 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

# Z**Z
# 2 << Z >> 2
# Z <- Z
# 1j*Z
# Z/1/1
# Z<Z>Z



z = np.array([1,1,2,3,4,3,2,1,9])

z**z # ok
2 << z >> 2 # ok
z <- z #ok but false
1j*z # ok
z/1/1 # ok but no sense
#z<z>z# no 


array([1., 1., 2., 3., 4., 3., 2., 1., 9.])

In [45]:
# 28. What are the result of the following expressions? (★☆☆)

# np.array(0) / np.array(0)
# np.array(0) // np.array(0)
# np.array([np.nan]).astype(int).astype(float)

print(np.array(0)/np.array(0))
print(np.array(0)//np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\plane\AppData\Local\Temp\ipykernel_21712\4248675537.py:7: RuntimeWarning: invalid value encountered in divide
  print(np.array(0)/np.array(0))
C:\Users\plane\AppData\Local\Temp\ipykernel_21712\4248675537.py:8: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0)//np.array(0))
C:\Users\plane\AppData\Local\Temp\ipykernel_21712\4248675537.py:9: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


In [8]:
# 29. How to round away from zero a float array ? # es decir, redondear al alza en valor absoluto
np.random.seed(42)
Z = np.random.uniform(low= -10,high= +10,size= 10) 
# Draw samples from a uniform distribution.
# Samples are uniformly distributed over the half-open interval [low, high) (includes low, but excludes high). 
# In other words, any value within the given interval is equally likely to be drawn by uniform.
print(Z)
print('\n')
print(np.copysign(np.ceil(np.abs(Z)), Z)) 

#np.copysign copia los signos del segundo array que le pasemos al primero
# np.ceil redondea hacia arriba los arrais, el problema biene con los arrais negativos que lo redondea que los redondea a valor absoluto mas pequeño

# More readable but less efficient
print(np.where(Z>0, np.ceil(Z), np.floor(Z)))

[-2.50919762  9.01428613  4.63987884  1.97316968 -6.87962719 -6.88010959
 -8.83832776  7.32352292  2.02230023  4.16145156]


[-3. 10.  5.  2. -7. -7. -9.  8.  3.  5.]
[-3. 10.  5.  2. -7. -7. -9.  8.  3.  5.]


In [25]:
# 30. How to find common values between two arrays? 

arr1 = np.random.randint(low= 0, high= 10, size= 10)
arr2 = np.random.randint(low= 0, high= 10, size= 10)

print(arr1)
print(arr2)

arr = set(np.where((arr1 in arr2), arr1, np.nan)) # no
print(arr)

[4 4 6 8 8 2 2 2 3 7]
[5 7 0 7 3 0 7 3 5 7]
{2.0, 3.0, 4.0, 6.0, 7.0, 8.0}


In [27]:
# este si

print(np.intersect1d(arr1, arr2))

[3 7]


In [31]:
# How to ignore all numpy warnings (not recommended)?

# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

In [34]:

# 32. Is the following expressions true? (★☆☆)

# np.sqrt(-1) == np.emath.sqrt(-1)
print(np.sqrt(-1))
print(np.emath.sqrt(-1))
#np.sqrt(-1) == np.emath.sqrt(-1)

nan
1j


C:\Users\plane\AppData\Local\Temp\ipykernel_8848\923986195.py:4: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1))
