In [2]:
import numpy as np

# Ejercicio 1

Tal y como ya hemos visto en clase, la variedad de herramientas proporcionadas por el algebra lineal son cruciales para desarrollar y fundamentar las bases de una variedad de técnicas relacionadas con el aprendizaje automático. Con ella, podemos describir el proceso de propagaci´on hacia adelante en una red neuronal, identificar ménimos locales en funciones multivariables (crucial para el proceso de retropropagación) o la descripción y empleo de métodos de reducción de la dimensionalidad, como el análisis de componentes principales (PCA), entre muchas otras aplicaciones. Cuando trabajamos en la práctica dentro de este ámbito, la cantidad de datos que manejamos puede ser muy grande, por lo que es especialmente importante emplear algoritmos eficientes y optimizados para reducir el coste computacional en la medida de lo posible. Por todo ello, el objetivo de este ejercicio es el de ilustrar las diferentes alternativas que pueden existir para realizar un proceso relacionado con el álgebra lineal y el impacto que puede tener cada variante en términos del coste computacional del mismo. En este caso en particular, y a modo de ilustración, nos centraremos en el cálculo del determinante de una matriz.

## A: [1 punto] Implementa una función, determinante recursivo, que obtenga el determinante de una matriz cuadrada utilizando la definición recursiva de Laplace.

In [1]:
def extraer_sub_mariz (m, col):                                  # Dada una casilla, extrae la submatriz o componente de la matriz adjunta
    sub_m = np.delete(m,0,0)
    sub_m = np.delete(sub_m, col, 1)

    return sub_m

def det_2x2(matrix):                                             # resuelve el determinante para una matriz 2x2
    if matrix.shape != (2,2):
        raise ValueError('shape error')
    
    return matrix[0,0]*matrix[1,1]-matrix[0,1]*matrix[1,0]

def determinante_laplace(M):                                     # Determinante recursivo

    if M.shape[0] == 1:
        return M
    
    elif M.shape[0] != M.shape[1]:                               # si la matriz no es cuadrada
        raise ValueError('invalid shape')
    
    elif M.shape == (2,2):                                       # si la matriz es de 2x2 devuelve directamente el determinante
        return det_2x2(M)
    
    det = 0
    signo = 1
    
    for col in range(len(M[0,:])):
        multiplicador =  M[0,col]                               # el valor de la fila 0 y la columna que le corresponde
        sub_M = extraer_sub_mariz(M, col= col)
        multiplicador *= determinante_laplace(sub_M)            # el multiplicador va a ser el determinante de la submatriz
        det += multiplicador*signo                              # se calcula el determinante por su correspondiente signo
        signo *= -1                                             # cambia el signo
    
    return det

In [3]:
np.random.seed(17)
M = np.random.randint(low= 0,high=10, size= (8,8))

print(M)
print('\n')
print(determinante_laplace(M))
print(round(np.linalg.det(M),0))

[[1 6 6 9 0 6 4 7]
 [4 7 1 1 9 8 2 3]
 [6 6 9 9 1 5 1 0]
 [5 6 6 2 6 9 8 3]
 [2 1 9 8 3 2 7 8]
 [9 2 1 8 1 8 0 4]
 [5 4 4 3 3 3 7 8]
 [5 1 9 4 9 7 3 3]]


7895784
7895784.0


## B: [0.5 puntos] Si A es una matriz cuadrada n×n y triangular (superior o inferior, es decir, con entradas nulas por debajo o por encima de la diagonal, respectivamente), ¿existe alguna forma de calcular de forma directa y sencilla su determinante? Justifíquese la respuesta.

Si una matriz es diagonal superior o inferior, el cálculo del determinante no es más que la multiplicación de los elementos que se encuentran en la diagonal principal. Esto ocurre así tanto por que en la mátriz principal como en las matrices inferiores, los únicos componentes no nulos son los que encontraremos en la diagonal, el resto se multiplicara por 0.

In [4]:
np.random.seed(42)
M_diagonal = np.random.randint(low= 1, high=10, size = (4,4))
M_diagonal= np.tril(M_diagonal, k= 0)
print(M_diagonal)
det= 1
for n in range(len(M_diagonal[0,:])):
    det*= M_diagonal[n,n]
print('\n')
print(det)
print(determinante_laplace(M_diagonal))


[[7 0 0 0]
 [7 3 0 0]
 [5 4 8 0]
 [3 6 5 2]]


336
336


## C: [0.5 puntos] DetermÍnese de forma justificada cómo alteran el determinante de una matriz n × n las dos operaciones elementales siguientes:

### Intercambiar una fila (o columna) por otra fila (o columna)

#### columna

In [5]:
np.random.seed(42)
M = np.random.randint(low= 1, high=10, size = (3,3))
print(M)
print('\n')
print(determinante_laplace(M))

a = M[:,0].copy()
b = M[:,1].copy()

M[:,0] =  b
M[:,1] =  a


print('\n')
print(M)
print('\n')
print(determinante_laplace(M))


[[7 4 8]
 [5 7 3]
 [7 8 5]]


-11


[[4 7 8]
 [7 5 3]
 [8 7 5]]


11



#### fila

In [6]:
np.random.seed(42)
M = np.random.randint(low= 1, high=10, size = (3,3))
print(M)
print('\n')
print(determinante_laplace(M))

a = M[0,:].copy()
b = M[1,:].copy()

M[0,:] =  b
M[1,:] =  a


print('\n')
print(M)
print('\n')
print(determinante_laplace(M))


[[7 4 8]
 [5 7 3]
 [7 8 5]]


-11


[[5 7 3]
 [7 4 8]
 [7 8 5]]


11


#### conclusión

cambiar una fila por otra, o una columna por otra cambia el signo, pero no altera el valor del determinante

### Sumar a una fila (o columna) otra fila (o columna) multiplicada por un escalar α.


#### columna

In [5]:
np.random.seed(42)
M = np.random.randint(low= 1, high=10, size = (3,3))
print(M)
print('\n')
print(determinante_laplace(M))

a = 2



M[:,1] += M[:,0]*a


print('\n')
print(M)
print('\n')
print(determinante_laplace(M))


[[7 4 8]
 [5 7 3]
 [7 8 5]]


-11


[[ 7 18  8]
 [ 5 17  3]
 [ 7 22  5]]


-11


#### por fila

In [8]:
np.random.seed(42)
M = np.random.randint(low= 1, high=10, size = (3,3))
print(M)
print('\n')
print(determinante_laplace(M))

a = 2



M[1,:] += M[0,:]*a


print('\n')
print(M)
print('\n')
print(determinante_laplace(M))

[[7 4 8]
 [5 7 3]
 [7 8 5]]


-11


[[ 7  4  8]
 [19 15 19]
 [ 7  8  5]]


-11


#### Conclusión

sumar a una columna (o fila), otra  multiplicada por un escalar no altera el determinante.

## D: [1 punto] Investiga sobre el método de eliminación de Gauss con pivoteo parcial e impleméntalo para escalonar una matriz (es decir, convertirla en una matriz triangular inferior) a partir de las operaciones elementales descritas en el apartado anterior.

    - Ir a la primera columna número cero de izquierda a derecha.
    - Si la primera fila tiene un cero en esta columna, intercambiarlo con otra que no lo tenga.
    - Luego, obtener ceros debajo de este elemento delantero, sumando múltiplos adecuados del renglón superior a los renglones debajo de él.
    - Cubrir el renglón superior y repetir el proceso anterior con la submatriz restante. Repetir con el resto de los renglones (en este punto la matriz se encuentra en forma escalonada).
    - Comenzando con el último renglón no cero, avanzar hacia arriba: para cada renglón obtener 1 delantero e introducir ceros arriba de este sumando múltiplos correspondientes a los renglones correspondientes.

Una variante interesante de la eliminación de Gauss es la que llamamos eliminación de Gauss-Jordan, (debido al mencionado Gauss y a Wilhelm Jordan), esta consiste en ir obteniendo los 1 delanteros durante los pasos uno al cuatro (llamados paso directo) así para cuando estos finalicen ya se obtendrá la matriz en forma escalonada reducida. 

## E: [0.5 puntos] ¿Cómo se podría calcular el determinante de una matriz haciendo beneficio de la estrategia anterior y del efecto de aplicar las operaciones elementales pertinentes? Implementa una nueva función, determinante gauss, que calcule el determinante de una matriz utilizando eliminación gaussiana.


Respondere la D y la E a la vez

In [9]:
np.random.seed(42)
M = np.random.randint(low= 1, high=10, size = (4,4))
print(M)

[[7 4 8 5]
 [7 3 7 8]
 [5 4 8 8]
 [3 6 5 2]]


In [10]:
def determinant_gauss_jordan_inf(M):

    if M.shape[0] != M.shape[1]:
        raise ValueError("La matriz no es cuadrada")            # si la matriz no es cuadrada dara error

    dimensiones = M.shape[0]
    M = M.astype(float)                                         # la paso a float para que las operaciones funcionen correctamente


    # empieza el método gauss Jordan
    for col in range(dimensiones-1):                            # no llega hasta la última columna
        pivote_diagonal = M[col,col]

        for linea in range(col+1, dimensiones):                 # la linea de eliminación siempre será la columna +1

            coeficiente = M[linea, col] / pivote_diagonal
            M[linea, :] -= coeficiente * M[col,: ]              # transformamos la línea restando su linea siguiente por el coeficiente calculado
    
    # calculo del determinante por la diagonal
    determinante = 1
    for numero in range(dimensiones):
        determinante *= M[numero,numero]
        
    #print(M)
    return round(determinante,0)


In [11]:
def determinante_gauss_jordan_sup(M):
    
    if M.shape[0] != M.shape[1]:
        raise ValueError('La matriz no es cuadrada')
    
    dimensiones = M.shape[0]
    M = M.astype(float)

    # empieza el método gauss Jordan
    for col in range(dimensiones -1, -1, -1):                   # no tocamos la ultima columna y la recorremos desde la penultima hasta la primera

        diagonal_pivote = M[col,col]
        if diagonal_pivote == 0:                                # el valor de la diagonal no debe ser 0, en tal caso habria que cambiar las filas de sitio
            continue 

        for linea in range(col-1, -1, -1):                      # no va a tocar la ultima fila, y tiene que ir de abajo hacia arriba para la triangulacion superior
            coeficiente = M[linea, col]/diagonal_pivote
            M[linea,:] -= coeficiente*M[col,:]                  # se modifica la linea restando la linea de la diagonal (linea -1) por el coeficiente calculado
    
    # calculo del determinante por la diagonal
    determinante = 1
    for numero in range(len(M[0,:])):
        determinante *= M[numero,numero]

    #print(M)
    return round(determinante,0)


#### Nota importante:

Esta es una funcion simplificada donde solo funcionara o calculara el valor correcto del determinante si no hay zeros en la diagonal. Por no complicarme más lo dejaré así

In [12]:
determinant_gauss_jordan_inf(M)

-251.0

In [13]:
determinante_gauss_jordan_sup(M)

-251.0

In [14]:
determinante_laplace(M)


-251

In [15]:
np.linalg.det(M)

-250.9999999999999

## [0.5 puntos] Obten la complejidad computacional asociada al cálculo del determinante con la definición recursiva y con el método de eliminación de Gauss con pivoteo parcial.


Partiendo de la siguiente tabla:

<img src="img/tabla_complejidad_comp.png" />

### La **complejidad computacional** asociada al calculo del determinante mediante el **método de Gauss**

La función hace uso de dos bucles for (en ralidad 3, pero el tercero es para el calculo del determinante por la diagonal, por lo que no escala de la misma manera que los demás);

                ###############################################################################################################################

    # empieza el método de gauss
    for col in range(dimensiones-1): # no llega hasta la última columna
        pivote_diagonal = M[col,col]

        for linea in range(col+1, dimensiones): # la linea de eliminación siempre será la columna +1

            coeficiente = M[linea, col] / pivote_diagonal
            M[linea, :] -= coeficiente * M[col,: ] 

                ###############################################################################################################################

Las iteraciones escalan en n dimeniones - 1 operaciones al cuadrado p.e, para las siguientes matrices:

 $ M(2x2) --->: (n-1)*(n-1) = 1*1 $ iteración

 $ M(3x3) --->: (n-1)*(n-1) = 2*2 $ iteraciones

 $ M(4x4) --->: (n-1)*(n-1) = 3*3 $ iteraciones
 
 etc.

 Por lo tanto, a medida que las entradas aumentan el número de iteraciones aumenta cuadráticamente, y sin tener en cuenta que la funcion no contempla el hecho de desplazar filas ni columnas en caso de que algun elemento de la diagonal sea 0, por lo que, un algoritmo más completo requeriría de más operaciones, de tal modo que para esta función la complejidad computacional será, de al menos: **$ O(n^2) $** o superior.


 ### La **complejidad computacional** asociada al calculo del determinante recursivo por el **método de laplace**

 La función hace uso de un solo bucle for, pero en cada bucle se llama a si misma: 


                ###############################################################################################################################

    det = 0
    signo = 1
    
    for col in range(len(M[0,:])):
        multiplicador =  M[0,col] # el valor de la fila 0 y la columna que le corresponde
        sub_M = extraer_sub_mariz(M, col= col)
        multiplicador *= determinante_laplace(sub_M)# el multiplicador va a ser el determinante de la submatriz
        det += multiplicador*signo # se calcula el determinante por su correspondiente signo
        signo *= -1 # cambia el signo
    
    return det

                ###############################################################################################################################

Las iteraciones escalan en n dimensiones, por cada vez que se llama la función, que esta tendra que hacer n - 1 iteraciones (pues es la submatriz de la primera), y así sucesivamente p.e, para las siguientes matrices:

 $ M(2x2) --->: (n)*(n-1) = 2*1 $ iteraciones

 $ M(3x3) --->: (n)*(n-1)*(n-2) = 3*2*1 $ iteraciones

 $ M(4x4) --->: (n)*(n-1)*(n-2)*(n-3) = 4*3*2*1 $ iteraciones

etc

De modo que a medida que aumentan las entradas (las dimensiones de la matriz) la operaciones a realizar aumentan factorialmente **$O(n!)$**

## G: [1 punto] Utilizando numpy.random.rand, genera matrices cuadradas aleatorias de la forma An ∈ Rn×n, para 2 ≤ n ≤ 10, y confecciona una tabla comparativa del tiempo de ejecución asociado a cada una de las variantes siguientes, interpretando los resultados: 

- Utilizando determinante recursivo.
- Empleando determinante gauss.
- Haciendo uso de la funci´on preprogramada numpy.linalg.det.


In [17]:
np.random.seed(42)
M2 = np.random.randint(low= 1, high= 10, size = (2,2))
M3 = np.random.randint(low= 1, high= 10, size = (3,3))
M4 = np.random.randint(low= 1, high= 10, size = (4,4))
M5 = np.random.randint(low= 1, high= 10, size = (5,5))
M6 = np.random.randint(low= 1, high= 10, size = (6,6))
M7 = np.random.randint(low= 1, high= 10, size = (7,7))
M8 = np.random.randint(low= 1, high= 10, size = (8,8))
M9 = np.random.randint(low= 1, high= 10, size = (9,9))
M10 = np.random.randint(low= 1, high= 10, size = (10,10))

In [18]:
import time

In [19]:
def tiempo_det_recursivo(M):
    start_time = time.time()
    determinante = determinante_laplace(M)
    end_time = time.time()
    execution_time = end_time - start_time
    return round(execution_time,4)

def tiempo_det_gauss(M):
    start_time = time.time()
    determinante = determinant_gauss_jordan_inf(M)
    end_time = time.time()
    execution_time = end_time - start_time
    return round(execution_time,4)

def tiempo_det_numpy(M):
    start_time = time.time()
    determinante = np.linalg.det(M)
    end_time = time.time()
    execution_time = end_time - start_time
    return round(execution_time,4)

In [20]:
lista_matrices = [M2,M3,M4,M5,M6,M7,M8,M9,M10]

In [24]:
print('\t\t\t\t\t TIEMPOS DE EJECUCIÓN DEL CALCULO DEL DETERMINANTE')
print('\n')

for M in lista_matrices:
    print(f'| \tMATRIX {M.shape[0]}X{M.shape[1]}\t|\tMétodo recursivo: {tiempo_det_recursivo(M)} s \t|\tMétodo gauss: {tiempo_det_gauss(M)} s\t|\tMétodo numpy: {tiempo_det_numpy(M)} s\t|')

					 TIEMPOS DE EJECUCIÓN DEL CALCULO DEL DETERMINANTE


| 	MATRIX 2X2	|	Método recursivo: 0.0 s 	|	Método gauss: 0.0 s	|	Método numpy: 0.0 s	|
| 	MATRIX 3X3	|	Método recursivo: 0.0 s 	|	Método gauss: 0.0 s	|	Método numpy: 0.0 s	|
| 	MATRIX 4X4	|	Método recursivo: 0.0 s 	|	Método gauss: 0.0 s	|	Método numpy: 0.0 s	|
| 	MATRIX 5X5	|	Método recursivo: 0.0 s 	|	Método gauss: 0.0 s	|	Método numpy: 0.0 s	|
| 	MATRIX 6X6	|	Método recursivo: 0.008 s 	|	Método gauss: 0.0 s	|	Método numpy: 0.0 s	|
| 	MATRIX 7X7	|	Método recursivo: 0.0475 s 	|	Método gauss: 0.0 s	|	Método numpy: 0.0 s	|
| 	MATRIX 8X8	|	Método recursivo: 0.3892 s 	|	Método gauss: 0.0 s	|	Método numpy: 0.0 s	|
| 	MATRIX 9X9	|	Método recursivo: 3.318 s 	|	Método gauss: 0.0 s	|	Método numpy: 0.0 s	|
| 	MATRIX 10X10	|	Método recursivo: 33.1429 s 	|	Método gauss: 0.0 s	|	Método numpy: 0.0 s	|


#### Conclusiones

para matrizes cuadradas de nxn dimensiones desde n = 2 hasta n = 10, el método recursivo de Laplace es único que da problemas, pues como se ha mencionado anteriormente, las operaciones a realizar crecen factorialmente, mientras que las del método de Gauss crecen entre cuadrática y cúbicamente. 

El método de numpy parece ser mejor o igual al metodo de Gauss, sin embargo, hay que recordar que el método de Gauss implementado esta simplificado, pues no dará un resultado correcto si en la diagonal se encuentra un 0, para eso habría que añadirle más operaciones, por lo que empeoraría el rendimiento un poco, haciendo más grande la brecha en este método y el de numpy, el cual esta optimizado al máximo.