In [1]:
import numpy as np
from sklearn.feature_selection import VarianceThreshold

In [3]:
# Carga de datos.
X = np.array(
    [[0, 0, 1],
     [0, 1, 0],
     [1, 0, 0],
     [0, 1, 1], 
     [0, 1, 0], 
     [0, 1, 1]]
)
print(X)

[[0 0 1]
 [0 1 0]
 [1 0 0]
 [0 1 1]
 [0 1 0]
 [0 1 1]]


In [14]:
# Limpieza de datos: selección de atributos.

# fijamos un umbral (th) para decidir qué porcentaje mínimo deben variar los valores de una columna para considerarse 
# una columna relevante a la hora de mantenerla en nuestro estudio
th_1 = 0.1
th_2 = 0.2
th_3 = 0.23
print(f'la varianza de la columna zero {round(X[:,0].var(), 2)}')
print(f'la varianza de la columna uno {round(X[:,1].var(), 2)}')
print(f'la varianza de la columna dos {round(X[:,2].var(), 2)}\n')
sel_1 = VarianceThreshold(th_1)
sel_2 = VarianceThreshold(th_2)
sel_3 = VarianceThreshold(th_3)
print(sel_1.fit_transform(X))
print('\n',  sel_2.fit_transform(X),)
print('\n',  sel_3.fit_transform(X),)

la varianza de la columna zero 0.14
la varianza de la columna uno 0.22
la varianza de la columna dos 0.25

[[0 0 1]
 [0 1 0]
 [1 0 0]
 [0 1 1]
 [0 1 0]
 [0 1 1]]

 [[0 1]
 [1 0]
 [0 0]
 [1 1]
 [1 0]
 [1 1]]

 [[1]
 [0]
 [0]
 [1]
 [0]
 [1]]
