In [1]:
import numpy as np
from sklearn.impute import SimpleImputer

In [11]:
# Carga de datos
X_train = np.array(
           [[1,      4], 
           [np.nan, 3], 
           [7,      8],
           [3,      np.nan],
           [-2,     -12],
           [11,     15],
           [np.nan, np.nan]])
print(X_train)

[[  1.   4.]
 [ nan   3.]
 [  7.   8.]
 [  3.  nan]
 [ -2. -12.]
 [ 11.  15.]
 [ nan  nan]]


In [12]:
# Limpieza de datos: imputación valores ausentes (modelo)
imputer = SimpleImputer(strategy='mean') # Utilizamos la estrategia de la media

# Aplicar los métodos "fit" y "transform" para imputar los valores pérdidos de X_train
# ???

imputer.fit(X_train)

X_train_clean = imputer.transform(X_train)

# tambien vale X_train_clean = imputer.fit_transform(X_train)

print(X_train_clean)

[[  1.    4. ]
 [  4.    3. ]
 [  7.    8. ]
 [  3.    3.6]
 [ -2.  -12. ]
 [ 11.   15. ]
 [  4.    3.6]]


In [13]:
# Imputación de valores ausentes sobre el conjunto de test
X_test = [[np.nan, 10], 
          [6,      np.nan], 
          [8,      2]]

# Imputar los datos del conjunto de test
# ???

X_test_clean = imputer.transform(X_test)

print(X_test_clean)

[[ 4.  10. ]
 [ 6.   3.6]
 [ 8.   2. ]]


### Un ejemplo más realista

In [14]:
import pandas as pd
import os

In [6]:
folder = 'C:/Users/plane/OneDrive/Escritorio/COMPUTING SCIENCE/MASTER Inteligencia artificial/05_Aprendizaje_supervisado/data'
f = 'penguins.csv'
path = os.path.join(folder, f)

df = pd.read_csv(path, sep= ';')

In [9]:
df.head()

CulmenLength  CulmenDepth  FlipperLength  BodyMass  Species
0          39.1         18.7          181.0    3750.0        0
1          39.5         17.4          186.0    3800.0        0
2          40.3         18.0          195.0    3250.0        0
3           NaN          NaN            NaN       NaN        0
4          36.7         19.3          193.0    3450.0        0

In [15]:
data = np.array(df)
print(data)

[[3.910e+01 1.870e+01 1.810e+02 3.750e+03 0.000e+00]
 [3.950e+01 1.740e+01 1.860e+02 3.800e+03 0.000e+00]
 [4.030e+01 1.800e+01 1.950e+02 3.250e+03 0.000e+00]
 ...
 [4.960e+01 1.820e+01 1.930e+02 3.775e+03 2.000e+00]
 [5.080e+01 1.900e+01 2.100e+02 4.100e+03 2.000e+00]
 [5.020e+01 1.870e+01 1.980e+02 3.775e+03 2.000e+00]]


In [18]:
pos_ausentes = np.unique(np.where(np.isnan(data))[0])

print(pos_ausentes)

[  3 271]


In [19]:
data[271,:]

array([nan, nan, nan, nan,  1.])

In [20]:
imputer = SimpleImputer(strategy= 'mean')
data_clean = imputer.fit_transform(data)

pos_ausentes = np.unique(np.where(np.isnan(data_clean)[0]))
print(pos_ausentes) # ya no hay ausentes

[]


## hacerlo mediante dataframes

In [26]:
imputer_2 = SimpleImputer(strategy='mean') # create

imputer_2.fit(df) # fit

df_no_nans = pd.DataFrame(data= imputer_2.transform(df), columns= df.columns)

display(df_no_nans.head())

CulmenLength  CulmenDepth  FlipperLength     BodyMass  Species
0      39.10000     18.70000     181.000000  3750.000000      0.0
1      39.50000     17.40000     186.000000  3800.000000      0.0
2      40.30000     18.00000     195.000000  3250.000000      0.0
3      43.92193     17.15117     200.915205  4201.754386      0.0
4      36.70000     19.30000     193.000000  3450.000000      0.0

In [27]:
df_no_nans.isna().any()

CulmenLength     False
CulmenDepth      False
FlipperLength    False
BodyMass         False
Species          False
dtype: bool

In [ ]:
df_array = imputer_2.transform()