In [1]:
from sklearn import preprocessing
import numpy as np

In [6]:
# Carga de datos.
X_train = np.array([[ 1., -1.,  2.],
                    [ 2.,  0.,  0.],
                    [ 0.,  1., -1.]])
np.random.seed(42)
X2_train = np.random.randint(low= -10, high=11, size= (3,3))

print(X_train)
print('\n')
print(X2_train)

[[ 1. -1.  2.]
 [ 2.  0.  0.]
 [ 0.  1. -1.]]


[[-4  9  4]
 [ 0 -3 10]
 [-4  8  0]]


In [7]:
# Limpieza de datos: estandarización.
standardizer = preprocessing.StandardScaler()       # create
scaler_2 = preprocessing.StandardScaler()

# Estandarizamos los datos de entrenamiento
# ???

standardizer.fit(X_train)                           # fit   
scaler_2.fit(X2_train)

X_train_scaled = standardizer.transform(X_train)    # transform
X2_train_scl = scaler_2.transform(X2_train)

print(X_train_scaled)
print('\n')
print(X2_train_scl)

[[ 0.         -1.22474487  1.33630621]
 [ 1.22474487  0.         -0.26726124]
 [-1.22474487  1.22474487 -1.06904497]]


[[-0.70710678  0.79708114 -0.16222142]
 [ 1.41421356 -1.41022048  1.29777137]
 [-0.70710678  0.61313934 -1.13554995]]


In [8]:
X_train_2 = np.array([[ 1., -1.,  2.],
                    [ 2.,  0.,  0.],
                    [ 0.,  1., -1.]])

In [9]:
# Aplicamos los métodos "fit" y "transform" por separado
# ???
# ???

X_train_scaled_2 = standardizer.fit_transform(X_train_2)

print(X_train_scaled_2)

[[ 0.         -1.22474487  1.33630621]
 [ 1.22474487  0.         -0.26726124]
 [-1.22474487  1.22474487 -1.06904497]]


In [10]:
# Comprobar si las matrices estandarizadas son iguales
# ???

print(X_train_scaled_2 == X_train_scaled)

print(np.array_equal(X_train_scaled, X_train_scaled_2))

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
True
