<font color="#002856"><h1 align="left">Algoritmos de optimización</h1></font>
<font color="#002856"><h2 align="left">VC-2 Diseño de algoritmos</h2></font> 

#### Profesor: Juan Francisco Vallalta Rueda
---

# Medir el tiempo de ejecución

Medir el tiempo de ejecución de un programa es una tarea muy importante, ya que programar no sólo consiste en crear código que funcione, sino código que pueda ser ejecutado en un tiempo razonable.

La librería **time** nos permite medir el tiempo de ejecución en Python, utilizando el método  `time()`.

In [1]:
# Medida del tiempo de ejecucion con time
import time
inicio = time.time()

# Código a medir
time.sleep(10)
# -------------

fin = time.time()
print(fin-inicio) # 1.0005340576171875

10.007688045501709


# Generación de números enteros aleatorios 

In [6]:
# Mödulo random
import random

# Inicialización del rango de números a generar
inicio= 0
fin = 1000
cantidad = 100

# Lista de números aleatorios
numeros_aleatorios = [random.randint(inicio,fin) for i in range(cantidad)]
print(numeros_aleatorios)

[695, 385, 928, 730, 82, 906, 416, 429, 707, 59, 556, 643, 489, 851, 385, 940, 465, 515, 942, 745, 219, 305, 8, 943, 218, 371, 483, 174, 136, 257, 482, 94, 385, 201, 530, 522, 460, 204, 882, 754, 24, 341, 576, 946, 97, 758, 491, 270, 746, 12, 652, 158, 483, 623, 710, 665, 856, 935, 963, 342, 247, 890, 673, 143, 54, 905, 868, 522, 1, 248, 690, 720, 363, 878, 567, 586, 593, 901, 574, 835, 853, 915, 188, 937, 489, 182, 228, 948, 247, 291, 223, 602, 741, 761, 199, 691, 72, 718, 965, 583]


# Ejercicios

## Implementa  una solución para el problema del cambio de moneda en un sistema monetario con las siguientes monedas: {1, 2, 5, 10, 20 , 50}

In [57]:
# Problema de cambio de monedas
def cambio_de_monedas(precio, pago, monedas= {0.01, 0.02, 0.05, 0.10, 0.20, 0.50}):

    vuelta = round(pago - precio, 2)
    print(vuelta)
    cambios_en_monedas = {}
    
    for n in range(len(monedas)):

        cambio_mas_alto_posible = max(monedas)
        n = vuelta//cambio_mas_alto_posible
        vuelta -= round((cambio_mas_alto_posible*n ), 2)    

        if vuelta == 0:
            break

        cambios_en_monedas[cambio_mas_alto_posible] = n
        monedas.remove(cambio_mas_alto_posible)

    return cambios_en_monedas




In [58]:
cambio_de_monedas(47.34,50)

2.66


{0.5: 5.0, 0.2: 0.0, 0.1: 1.0, 0.05: 1.0, 0.02: 0.0, 0.01: 1.0}

# Reto VC-2

## Opción 1: Implementa una solución al problema de las 8 reinas en un tablero 8x8

In [1]:
import numpy as np

In [2]:
tablero = np.zeros(16).reshape(4,4)
print(tablero)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [3]:
def colocar_reina(m, fila, col ,tab):

    '''
    esta funcion coloca una reina en un tablero de ajedrez donde las posiciones que no estan en peligro son 0s, la casilla donde se coloca la reina será un numero de un dígito, 
    y las casillas en peligro serán un numero de dos digitos. La función devuelve el tablero con la nueva reina colocada y sus posiciones de peligro.
    '''

    
    # las zonas en peligro seran m +10 para que tenga dos digitos y se pueda diferenciar
    tab[fila,:] = m +10                                                 # zona de peligro horizontal
    tab[:, col] = m +10                                                 # zona de peligro vertical

    # colocamos la reina
    tab[fila, col] = m

    # las diagonales
    diag_c1 = min((tab.shape[0]-1)-col,fila)
    diag_c2 = min(col,fila)
    diag_c3 = min(col, (tab.shape[0]-1)-fila)
    diag_c4= min((tab.shape[0]-1)-col, (tab.shape[0]-1)-fila)

    # cuadrante 1
    for n in range(1,diag_c1+1):
        tab[fila -n, col + n] = m +10

    # cuadrante 2
    for n in range(1,diag_c2+1):
        tab[fila -n, col-n] = m +10

    # cuadrate 3
    for n in range(1,diag_c3+1):
        tab[fila +n, col-n] = m +10

    # cuadrante 4
    for n in range(1,diag_c4+1):
        tab[fila +n, col+n] = m +10

    return tab

In [4]:
def algoritmo_n_reinas(n, tablero):

    if n < 1:
        return True
    
    if np.count_nonzero(tablero == 0) < n:                                              # Si hay menos 0s que reinas 
        return False
    
    
    for fila in range(tablero.shape[0]):                                                # para cada fila de la matriz
        for col in range(tablero.shape[1]):                                             # para cada columna de la matriz

            if tablero[fila,col] == 0:                                                  # si la casilla es 0

                tablero_viejo = tablero.copy()                                          # creo un tablero copia para poder hacer el backtraking
                tablero_actual = colocar_reina(np.random.randint(low= 1, high= 10), fila, col, tablero)      # coloco una nueva reina en el tablero en una posición valida por ahora

                if algoritmo_n_reinas(n-1, tablero_actual):                                    # aplico la recursividad
                    return True
                
                else:                                                                   # si la función falla el tablero vuelve a ser el mismo que antes de colocar la reina
                    tablero = tablero_viejo

    return False

In [7]:
tablero = np.zeros(25).reshape(5,5)

algoritmo_n_reinas(5, tablero)

print(tablero)

[[ 8. 14. 18. 15. 14.]
 [15. 14.  3. 15. 18.]
 [14. 15. 14. 15.  8.]
 [14.  4. 15. 15. 15.]
 [15. 15. 15.  5. 15.]]


In [8]:
tablero = np.zeros(16).reshape(4,4)

print(np.count_nonzero(tablero == 0))

print(colocar_reina(1,1,0,tablero))
print('\n')

np.count_nonzero(tablero == 0)

16
[[11. 11.  0.  0.]
 [ 1. 11. 11. 11.]
 [11. 11.  0.  0.]
 [11.  0. 11.  0.]]




6

In [23]:
def factible_choices(tablero):

    fact_choices = []
    size = tablero.shape[0]

    for fila in range(size):

        if 0 not in tablero[fila,:]:
            continue

        for col in range(size):

            if 0 not in tablero[:, col]:
                continue

            if tablero[fila,col] == 0:
                fact_choices.append([fila, col])

    return fact_choices
print(tablero)
print('\n')
fc = factible_choices(tablero)
print(fc)
cl = random.choice(fc)
print(cl)
fc.remove(cl)
print('\n')
print(fc)


[[11. 11.  0.  0.]
 [ 1. 11. 11. 11.]
 [11. 11.  0.  0.]
 [11.  0. 11.  0.]]


[[0, 2], [0, 3], [2, 2], [2, 3], [3, 1], [3, 3]]
[2, 3]


[[0, 2], [0, 3], [2, 2], [3, 1], [3, 3]]


In [17]:
import random

In [63]:
def n_reinas(n, tablero):

    if n<1:
        return True
    
    if np.count_nonzero(tablero == 0) < n:
        return False
    
    casillas_factibles = factible_choices(tablero)
    tablero_viejo = tablero.copy()

    while len(casillas_factibles) >0:

        casilla_elegida = random.choice(casillas_factibles)
        fila = casilla_elegida[0]
        col = casilla_elegida[1]
        tablero_nuevo = colocar_reina(np.random.randint(low= 1, high= 10), fila, col, tablero)

        if n_reinas(n-1, tablero_nuevo):
            print(casilla_elegida)
            return True
        
        else:
            casillas_factibles.remove(casilla_elegida)
            tablero = tablero_viejo.copy()

    return False

In [68]:
reinas = 15
tablero = np.zeros((reinas,reinas), dtype= int)

n_reinas(reinas, tablero)
#print(tablero)

[9, 0]
[5, 10]
[2, 12]
[11, 9]
[10, 3]
[8, 14]
[4, 1]
[3, 5]
[14, 13]
[12, 4]
[7, 11]
[0, 7]
[1, 2]
[13, 8]
[6, 6]


True

## comprobando la función colocar reina

In [29]:
tablero = np.zeros(16).reshape(4,4)
print(tablero)
print(np.count_nonzero(tablero== 0))
print('\n')

print(colocar_reina(1,1,0, tablero))
print(np.count_nonzero(tablero== 0))
print('\n')

print(colocar_reina(3,3,1, tablero))
print(np.count_nonzero(tablero== 0))
print('\n')
print(colocar_reina(9,0,2, tablero))
print(np.count_nonzero(tablero== 0))
print('\n')
print(colocar_reina(2,2,3, tablero))
print(np.count_nonzero(tablero== 0))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
16


[[11. 11.  0.  0.]
 [ 1. 11. 11. 11.]
 [11. 11.  0.  0.]
 [11.  0. 11.  0.]]
6


[[11. 13.  0.  0.]
 [ 1. 13. 11. 13.]
 [13. 13. 13.  0.]
 [13.  3. 13. 13.]]
3


[[19. 19.  9. 19.]
 [ 1. 19. 19. 19.]
 [19. 13. 19.  0.]
 [13.  3. 19. 13.]]
1


[[19. 12.  9. 12.]
 [ 1. 19. 12. 12.]
 [12. 12. 12.  2.]
 [13.  3. 12. 12.]]
0


In [75]:
tab = np.zeros(64).reshape(8,8)
print(tab)
print('\n')
print(colocar_reina(3,7,4,tab))
print('\n')
print(colocar_reina(2,1,0,tab))
print('\n')
print(colocar_reina(1,6,1,tab))
print('\n')
print(colocar_reina(5,0,2,tab))
print('\n')
print(colocar_reina(9,3,3,tab))
print('\n')
print(colocar_reina(7,4,5,tab))
print('\n')
print(colocar_reina(8,2,6,tab))


[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


[[ 0.  0.  0.  0. 13.  0.  0.  0.]
 [ 0.  0.  0.  0. 13.  0.  0.  0.]
 [ 0.  0.  0.  0. 13.  0.  0.  0.]
 [13.  0.  0.  0. 13.  0.  0.  0.]
 [ 0. 13.  0.  0. 13.  0.  0. 13.]
 [ 0.  0. 13.  0. 13.  0. 13.  0.]
 [ 0.  0.  0. 13. 13. 13.  0.  0.]
 [13. 13. 13. 13.  3. 13. 13. 13.]]


[[12. 12.  0.  0. 13.  0.  0.  0.]
 [ 2. 12. 12. 12. 12. 12. 12. 12.]
 [12. 12.  0.  0. 13.  0.  0.  0.]
 [12.  0. 12.  0. 13.  0.  0.  0.]
 [12. 13.  0. 12. 13.  0.  0. 13.]
 [12.  0. 13.  0. 12.  0. 13.  0.]
 [12.  0.  0. 13. 13. 12.  0.  0.]
 [12. 13. 13. 13.  3. 13. 12. 13.]]


[[12. 11.  0.  0. 13.  0.  0. 11.]
 [ 2. 11. 12. 12. 12. 12. 11. 12.]
 [12. 11.  0.  0. 13. 11.  0.  0.]
 [12. 11. 12.  0. 11.  0.  0.  0.]
 [12. 11.  0. 11. 13.  0.  0. 13.]
 [11. 11. 11.  0. 12.  0. 13.  0.]
 [11.

## Opción 2: Implementa una solución del problema de las Torres de Hanoi para un número arbitrario n de fichas

In [2]:
# Torres de Hanoy
# Escribe aquí tu código


